# This is a basic workflow to help you get started with Actions

name: CI

on: [push]

env:
  ESBUILD: esbuild --outfile=(mktemp) --log-override:css-syntax-error=error

jobs:
  strings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npx $ESBUILD strings.json 

  broken-features:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npx csval broken-features.csv

  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npx $ESBUILD style/*
